### ISSUE TITLE
nsp implodes if you specify an invalid reporter name

### ISSUE THREAD

**Issue by pdehaan** [requiresafe/grunt-requiresafe#11]
For fun, I set my output reporter/formatter as "summaryz". This happens:

``` sh
✗ grunt nsp

Running "nsp" task
fxa-content-server.CRITICAL: uncaughtException TypeError: undefined is not a function
    at /Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/grunt-nsp/tasks/nsp.js:44:20
    at /Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/grunt-nsp/node_modules/nsp/lib/check.js:214:7
    at /Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/grunt-nsp/node_modules/nsp/node_modules/wreck/lib/index.js:472:20
    at finish (/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/grunt-nsp/node_modules/nsp/node_modules/wreck/lib/index.js:326:16)
    at wrapped (/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/grunt-nsp/node_modules/nsp/node_modules/hoek/lib/index.js:866:20)
    at onReaderFinish (/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/grunt-nsp/node_modules/nsp/node_modules/wreck/lib/index.js:363:16)
    at g (events.js:199:16)
    at emit (events.js:129:20)
    at finishMaybe (_stream_writable.js:484:14)
    at endWritable (_stream_writable.js:493:3)
    at Writable.end (_stream_writable.js:459:5)
    at IncomingMessage.onend (_stream_readable.js:505:10)
    at IncomingMessage.g (events.js:199:16)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
Fatal error: undefined is not a function
```

We may want to add a quick check to make sure that the user specified a valid reporter.

**Comment by evilpacket** [comment]
yup. I went for quick and dirty. I'll fix that up :)

I'm thinking I'll just print a warning and continue with the default reporter. Good?

**Comment by pdehaan** [comment]
Yeah, sounds great, thanks.
