### ISSUE TITLE
Errors when running ESLint

### ISSUE THREAD

**Issue by pdehaan** [requiresafe/grunt-requiresafe#13]
Did ye olde `git clone` and `npm install` (Node 0.12), and got the following:

``` sh
$ npm run lint

> grunt-nsp@2.1.0 lint /Users/pdehaan/dev/github/grunt-nsp
> eslint .

/Users/pdehaan/dev/github/grunt-nsp/node_modules/eslint/lib/config.js:213
                    throw e;
                          ^
Error: Cannot find module 'eslint-config-hapi'
Referenced from: nodesecurity/es5
Referenced from: /Users/pdehaan/dev/github/grunt-nsp/.eslintrc
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at readConfigFromFile (/Users/pdehaan/dev/github/grunt-nsp/node_modules/eslint/lib/config.js:155:44)
    at loadConfig (/Users/pdehaan/dev/github/grunt-nsp/node_modules/eslint/lib/config.js:176:22)
    at /Users/pdehaan/dev/github/grunt-nsp/node_modules/eslint/lib/config.js:207:46
    at Array.reduceRight (native)
    at loadConfig (/Users/pdehaan/dev/github/grunt-nsp/node_modules/eslint/lib/config.js:191:36)
    at /Users/pdehaan/dev/github/grunt-nsp/node_modules/eslint/lib/config.js:207:46

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/pdehaan/.nvm/versions/node/v0.12.7/bin/node" "/Users/pdehaan/.nvm/versions/node/v0.12.7/bin/npm" "run" "lint"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! grunt-nsp@2.1.0 lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grunt-nsp@2.1.0 lint script 'eslint .'.
npm ERR! This is most likely a problem with the grunt-nsp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint .
npm ERR! You can get their info via:
npm ERR!     npm owner ls grunt-nsp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pdehaan/dev/github/grunt-nsp/npm-debug.log


$ npm ls --depth 0
grunt-nsp@2.1.0 /Users/pdehaan/dev/github/grunt-nsp
├── eslint@1.8.0
├── eslint-config-nodesecurity@1.0.0
├── grunt@0.4.5
├── grunt-cli@0.1.13
├── nsp@2.0.1
└── shrinkydink@1.0.0
```

**Comment by pdehaan** [comment]
IIUC, we'll need to add **eslint-config-hapi** and **eslint-plugin-hapi** as devDependencies of each repo that uses this config. I can't find any way to bundle those dependencies (or at least the eslint-plugin-hapi) into the custom **eslint-config-nodesecurity** module.

**Comment by nlf** [comment]
hmm.. is this still an issue? we've made some changes to our linting setup, so maybe it was fixed inadvertently? if not, i'll check it out and see what i can come up with.

**Comment by pdehaan** [comment]
Looks like I don't see errors, but I do get two warnings:

```
➜  grunt-nsp git:(master) npm run lint

> grunt-nsp@2.1.2 lint /Users/pdehaan/dev/github/grunt-nsp
> eslint .


/Users/pdehaan/dev/github/grunt-nsp/tasks/nsp.js
  27:14  warning  Closing curly brace appears on the same line as the subsequent block  brace-style
  46:14  warning  Closing curly brace appears on the same line as the subsequent block  brace-style

✖ 2 problems (0 errors, 2 warnings)
```
